import { 
  Layers, Activity, Gem, MessageSquare, Network, Ticket, Paintbrush, 
  FileText, AlertTriangle, Kanban, Database,
  Calculator, Sparkles, Receipt, Coins, Scale, Clock, 
  FileSignature, Briefcase, Landmark, Send, Globe, 
  Calendar, UserPlus, TrendingUp, ShieldCheck, ShieldAlert, Server, Repeat, Key,
  MessageSquareQuote, Users, Hash, LayoutDashboard, 
  Flame, Percent, ListTodo, CreditCard, Search, Type, Code, Palette, Package, Heart, Zap, Link, FileCode, FileSearch, Lock
} from 'lucide-react';
import { Tool, Category } from '../types';

export const CATEGORIES: Category[] = [
  { id: 'finance', name: 'Finance & Billing', description: 'Rates, taxes, invoicing, and expense tracking.' },
  { id: 'sales', name: 'Sales & Proposals', description: 'Pitching, proposals, and client acquisition.' },
  { id: 'legal', name: 'Legal & Scoping', description: 'Contracts, NDAs, and project scoping.' },
  { id: 'marketing', name: 'Marketing & Growth', description: 'CPA, ROI, and performance calculators.' },
  { id: 'development', name: 'SEO & Dev', description: 'SEO kits, technical stacks, and site audits.' },
  { id: 'security', name: 'Security & Compliance', description: 'Risk audits, calculators, and hardening tools.' },
  { id: 'operations', name: 'Operations & PM', description: 'Timelines, capacity, and project management.' },
];

export const getCategorySlug = (categoryId: string) => {
  const category = CATEGORIES.find(c => c.id === categoryId);
  if (!category) return categoryId;
  return category.name.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
};

export const getCategoryIdFromSlug = (slug: string) => {
  if (!slug || slug === 'All') return 'All';
  const category = CATEGORIES.find(c => getCategorySlug(c.id) === slug);
  return category ? category.id : slug;
};

export const TOOLS: Tool[] = [
  {
    id: 'rate-calc',
    slug: 'freelance-rate-calculator',
    name: 'Freelance Rate Calculator',
    description: 'Calculate your exact hourly rate based on income goals, expenses, and taxes.',
    category: 'finance',
    icon: Calculator,
    tier: 'FREE',
    hasAI: false,
    component: 'RateCalculator',
    outputType: 'Data Table',
    persona: 'Independent',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 3200,
    usageCount: 2137,
    audience: 'Creative Studio'
  },
  {
    id: 'proposal-gen',
    slug: 'ai-proposal-generator',
    name: 'AI Proposal Generator',
    description: 'Generate a professional freelance proposal in seconds with AI.',
    category: 'sales',
    icon: Sparkles,
    tier: 'FREEMIUM',
    hasAI: true,
    component: 'ProposalGenerator',
    outputType: 'PDF Export',
    persona: 'Freelancer',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 4500,
    usageCount: 2875,
    audience: 'Solo Freelancer'
  },
  {
    id: 'invoice-gen',
    slug: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Create and download professional invoices without watermarks.',
    category: 'finance',
    icon: Receipt,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'InvoiceGenerator',
    outputType: 'PDF / Link',
    persona: 'Business Owner',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 2800,
    usageCount: 1379,
    audience: 'Solo Freelancer'
  },
  {
    id: 'cost-estimator',
    slug: 'project-cost-estimator',
    name: 'Project Cost Estimator',
    description: 'Estimate project costs by breaking down tasks and adding buffers.',
    category: 'operations',
    icon: Coins,
    tier: 'FREE',
    hasAI: false,
    component: 'CostEstimator',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 1200,
    usageCount: 4161,
    audience: 'Dev Agency'
  },
  {
    id: 'late-payment',
    slug: 'late-payment-calculator',
    name: 'Late Payment Tool',
    description: 'Calculate interest and fees for overdue invoices.',
    category: 'legal',
    icon: Scale,
    tier: 'FREE',
    hasAI: false,
    component: 'LatePaymentCalculator',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 950,
    usageCount: 838,
    audience: 'Solo Freelancer'
  },
  {
    id: 'billable-tracker',
    slug: 'billable-hours-tracker',
    name: 'Billable Hours Tracker',
    description: 'Track your hours and sync them to your projects.',
    category: 'operations',
    icon: Clock,
    tier: 'FREE',
    hasAI: false,
    component: 'BillableTracker',
    personas: ['engineer'],
    monthlyViews: 1550,
    usageCount: 145,
    audience: 'Dev Agency'
  },
  {
    id: 'contract-builder',
    slug: 'contract-builder',
    name: 'Contract Agreement Builder',
    description: 'Draft simple, enforceable freelance service agreements and NDAs.',
    category: 'legal',
    icon: FileSignature,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'ContractBuilder',
    outputType: 'Legal Doc',
    persona: 'Legal Mind',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 1800,
    usageCount: 4066,
    audience: 'Dev Agency'
  },
  {
    id: 'portfolio-builder',
    slug: 'ai-portfolio-case-study-builder',
    name: 'AI Portfolio Builder',
    description: 'Input raw notes and get a professional STAR case study for your portfolio.',
    category: 'sales',
    icon: Briefcase,
    tier: 'FREEMIUM',
    hasAI: true,
    component: 'PortfolioBuilder',
    personas: ['designer'],
    monthlyViews: 2200,
    usageCount: 2850,
    audience: 'Solo Freelancer'
  },
  {
    id: 'tax-estimator',
    slug: 'freelance-tax-estimator',
    name: 'Freelance Tax Estimator',
    description: 'Estimate your quarterly tax payments and self-employment deductions.',
    category: 'finance',
    icon: Landmark,
    tier: 'FREE',
    hasAI: false,
    component: 'TaxEstimator',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 1400,
    usageCount: 4025,
    audience: 'Creative Studio'
  },
  {
    id: 'follow-up-gen',
    slug: 'ai-follow-up-email-generator',
    name: 'AI Follow-up Generator',
    description: 'AI-powered scripts for overdue invoices and lead nurturing.',
    category: 'sales',
    icon: Send,
    tier: 'FREEMIUM',
    hasAI: true,
    component: 'FollowUpEmailGenerator',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 1300,
    usageCount: 2092,
    audience: 'Solo Freelancer'
  },
  {
    id: 'currency-converter',
    slug: 'currency-rate-converter',
    name: 'Currency Rate Converter',
    description: 'Live exchange rates for 160+ currencies with historical parity.',
    category: 'finance',
    icon: Globe,
    tier: 'FREE',
    hasAI: false,
    component: 'CurrencyConverter',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 600,
    usageCount: 3145,
    audience: 'Solo Freelancer'
  },
  {
    id: 'timeline-generator',
    slug: 'project-timeline-generator',
    name: 'Project Timeline Gen',
    description: 'Generate Gantt-style visual timelines for client milestones.',
    category: 'operations',
    icon: Calendar,
    tier: 'FREE',
    hasAI: false,
    component: 'TimelineGenerator',
    personas: ['engineer'],
    monthlyViews: 1100,
    usageCount: 594,
    audience: 'Creative Studio'
  },
  {
    id: 'onboarding-checklist',
    slug: 'client-onboarding-checklist',
    name: 'Onboarding Checklist',
    description: 'Custom client workflows and onboarding trackers.',
    category: 'sales',
    icon: UserPlus,
    tier: 'FREE',
    hasAI: false,
    component: 'OnboardingChecklist',
    personas: ['agency'],
    monthlyViews: 800,
    usageCount: 1744,
    audience: 'Solo Freelancer'
  },
  {
    id: 'income-goal-planner',
    slug: 'annual-income-goal-planner',
    name: 'Annual Goal Planner',
    description: 'Reverse-calculate your fees based on desired annual income.',
    category: 'finance',
    icon: TrendingUp,
    tier: 'FREE',
    hasAI: false,
    component: 'IncomeGoalPlanner',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 1250,
    usageCount: 3988,
    audience: 'Dev Agency'
  },
  {
    id: 'privacy-policy-gen',
    slug: 'privacy-policy-generator',
    name: 'Privacy Policy Gen',
    description: 'Generate GDPR-compliant privacy policies for your website.',
    category: 'legal',
    icon: ShieldCheck,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'PrivacyPolicyGenerator',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 750,
    usageCount: 1568,
    audience: 'Dev Agency'
  },
  {
    id: 'retainer-builder',
    slug: 'retainer-agreement-builder',
    name: 'Retainer Builder',
    description: 'Create recurring revenue agreements for long-term clients.',
    category: 'legal',
    icon: Repeat,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'RetainerBuilder',
    personas: ['agency'],
    monthlyViews: 1100,
    usageCount: 4268,
    audience: 'Solo Freelancer'
  },
  {
    id: 'testimonial-gen',
    slug: 'ai-testimonial-request-generator',
    name: 'AI Testimonial Tool',
    description: 'Generate high-converting testimonial request scripts with AI.',
    category: 'sales',
    icon: MessageSquareQuote,
    tier: 'FREEMIUM',
    hasAI: true,
    component: 'TestimonialRequestGenerator',
    personas: ['designer', 'agency'],
    monthlyViews: 1450,
    usageCount: 1307,
    audience: 'Dev Agency'
  },
  {
    id: 'capacity-planner',
    slug: 'agency-capacity-planner',
    name: 'Agency Capacity Planner',
    description: 'Manage team hours and project bandwidth in one dashboard.',
    category: 'operations',
    icon: Users,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'CapacityPlanner',
    personas: ['agency'],
    monthlyViews: 2100,
    usageCount: 4838,
    audience: 'Solo Freelancer'
  },
  {
    id: 'project-number-gen',
    slug: 'project-number-generator',
    name: 'Project Number Gen',
    description: 'Format and generate professional project/invoice numbers.',
    category: 'sales',
    icon: Hash,
    tier: 'FREE',
    hasAI: false,
    component: 'ProjectNumberGenerator',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 550,
    usageCount: 2903,
    audience: 'Creative Studio'
  },
  {
    id: 'project-dashboard',
    slug: 'client-project-dashboard',
    name: 'Client Progress Dashboard',
    description: 'A read-only link for clients to track project milestones.',
    category: 'operations',
    icon: LayoutDashboard,
    tier: 'FREE',
    hasAI: false,
    component: 'ProjectDashboard',
    personas: ['agency'],
    monthlyViews: 900,
    usageCount: 499,
    audience: 'Dev Agency'
  },
  {
    id: 'financial-runway',
    slug: 'financial-runway-calculator',
    name: 'Runway & Burn Calculator',
    description: 'Calculate your "survival" cash based on burn rate.',
    category: 'finance',
    icon: Flame,
    tier: 'FREE',
    hasAI: false,
    component: 'RunwayCalculator',
    personas: ['agency'],
    monthlyViews: 1050,
    usageCount: 2248,
    audience: 'Dev Agency'
  },
  {
    id: 'markup-calc',
    slug: 'markup-margin-calculator',
    name: 'Profit Margin Calculator',
    description: 'Calculate gross profit and net margins for your work.',
    category: 'finance',
    icon: Percent,
    tier: 'FREE',
    hasAI: false,
    component: 'ProfitMarginCalculator',
    personas: ['agency'],
    monthlyViews: 850,
    usageCount: 1174,
    audience: 'Creative Studio'
  },
  {
    id: 'timezone-converter',
    slug: 'global-timezone-converter',
    name: 'Global Timezone Converter',
    description: 'Convert times across multiple client timezones.',
    category: 'operations',
    icon: Globe,
    tier: 'FREE',
    hasAI: false,
    component: 'TimezoneConverter',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 300,
    usageCount: 1210,
    audience: 'Solo Freelancer'
  },
  {
    id: 'task-prioritizer',
    slug: 'eisenhower-matrix-prioritizer',
    name: 'Task Priority Matrix',
    description: 'Prioritize tasks using the Eisenhower Urgency matrix.',
    category: 'operations',
    icon: ListTodo,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'TaskPriorityMatrix',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 1200,
    usageCount: 3533,
    audience: 'Creative Studio'
  },
  {
    id: 'expense-tool',
    slug: 'business-expense-tool',
    name: 'Business Expense Tracker',
    description: 'Track and categorize your business expenses.',
    category: 'finance',
    icon: CreditCard,
    tier: 'FREE',
    hasAI: false,
    component: 'ExpenseTool',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 1700,
    usageCount: 946,
    audience: 'Solo Freelancer'
  },
  {
    id: 'seo-kit',
    slug: 'freelance-seo-kit',
    name: 'SEO & Meta Tag Kit',
    description: 'Generate SEO tags and UTM params for your portfolio.',
    category: 'development',
    icon: Search,
    tier: 'FREE',
    hasAI: false,
    component: 'SEOKit',
    personas: ['designer', 'agency'],
    monthlyViews: 1600,
    usageCount: 1407,
    audience: 'Creative Studio'
  },
  {
    id: 'platform-arbitrage',
    slug: 'platform-arbitrage-calculator',
    name: 'Platform Arbitrage Calculator',
    description: 'Reverse-calculate platform fees (Upwork/Fiverr) to find your true target bid.',
    category: 'finance',
    icon: Percent,
    tier: 'FREE',
    hasAI: false,
    component: 'ArbitrageCalculator',
    personas: ['engineer', 'designer'],
    monthlyViews: 900,
    usageCount: 1932,
    audience: 'Creative Studio'
  },
  {
    id: 'framework-matrix',
    slug: 'technical-framework-matrix',
    name: 'The Framework Matrix',
    description: 'Generate technical stack recommendations to pitch and justify architectures.',
    category: 'sales',
    icon: Layers,
    tier: 'FREEMIUM',
    hasAI: true,
    component: 'FrameworkMatrix',
    personas: ['engineer'],
    monthlyViews: 1400,
    usageCount: 1535,
    audience: 'Solo Freelancer'
  },
  {
    id: 'seo-recovery',
    slug: 'algorithmic-recovery-auditor',
    name: 'Algorithmic Recovery Auditor',
    description: 'Diagnose traffic drops, identify exact Google updates, and generate a procedural recovery roadmap.',
    category: 'development',
    icon: Activity,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'AlgorithmicRecovery',
    personas: ['agency'],
    monthlyViews: 1200,
    usageCount: 781,
    audience: 'Creative Studio'
  },
  {
    id: 'asset-vault',
    slug: 'client-brand-asset-vault',
    name: 'Brand Asset Vault Builder',
    description: 'Generate a secure, read-only dashboard deliverable for final client assets.',
    category: 'sales',
    icon: Gem,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'AssetVault',
    personas: ['designer', 'agency'],
    monthlyViews: 1500,
    usageCount: 2010,
    audience: 'Creative Studio'
  },
  {
    id: 'cold-pitch',
    slug: 'cold-pitch-framework-gen',
    name: 'Cold Pitch Framework Gen',
    description: 'Draft highly converting outbound emails focused entirely on client pain points.',
    category: 'sales',
    icon: MessageSquare,
    tier: 'FREE',
    hasAI: true,
    component: 'ColdPitchGenerator',
    personas: ['engineer', 'designer', 'agency'],
    monthlyViews: 2000,
    usageCount: 302,
    audience: 'Creative Studio'
  },
  {
    id: 'erp-scoper',
    slug: 'erp-api-integration-scoper',
    name: 'ERP/API Integration Scoper',
    description: 'Calculate complexity multipliers and padded timelines for deep system integrations.',
    category: 'operations',
    icon: Network,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'IntegrationScoper',
    personas: ['engineer', 'agency'],
    monthlyViews: 1100,
    usageCount: 2161,
    audience: 'Creative Studio'
  },
  {
    id: 'revision-tracker',
    slug: 'client-revision-token-tracker',
    name: 'Revision Token Tracker',
    description: 'Visually track client revisions and lock scopes to prevent endless tweaks.',
    category: 'operations',
    icon: Ticket,
    tier: 'FREE',
    hasAI: false,
    component: 'RevisionTracker',
    personas: ['designer', 'agency'],
    monthlyViews: 450,
    usageCount: 681,
    audience: 'Dev Agency'
  },
  {
    id: 'handoff-gen',
    slug: 'design-to-dev-handoff-gen',
    name: 'Design-to-Dev Handoff Generator',
    description: 'Standardize asset, hex code, and typography transfers for developers.',
    category: 'operations',
    icon: Paintbrush,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'HandoffGenerator',
    personas: ['designer', 'engineer'],
    monthlyViews: 1000,
    usageCount: 2987,
    audience: 'Solo Freelancer'
  },
  {
    id: 'content-brief',
    slug: 'content-brief-automation',
    name: 'Content Brief Automation',
    description: 'Generate strict structural markdown briefs for writers and AI generation.',
    category: 'operations',
    icon: FileText,
    tier: 'FREEMIUM',
    hasAI: true,
    component: 'ContentBriefGen',
    personas: ['agency'],
    monthlyViews: 2200,
    usageCount: 4534,
    audience: 'Creative Studio'
  },
  {
    id: 'cannibalization-risk',
    slug: 'seo-cannibalization-risk-detector',
    name: 'Cannibalization Risk Detector',
    description: 'Cross-reference URLs and target keywords to flag overlapping SEO content.',
    category: 'operations',
    icon: AlertTriangle,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'CannibalizationDetector',
    personas: ['agency'],
    monthlyViews: 1150,
    usageCount: 2928,
    audience: 'Solo Freelancer'
  },
  {
    id: 'task-triage',
    slug: 'full-stack-task-triage',
    name: 'Full-Stack Task Triage',
    description: 'Drag-and-drop Eisenhower matrix to visually manage chaotic agency workloads.',
    category: 'operations',
    icon: Kanban,
    tier: 'FREE',
    hasAI: false,
    component: 'FullStackTaskTriage',
    personas: ['engineer', 'agency'],
    monthlyViews: 1400,
    usageCount: 2478,
    audience: 'Solo Freelancer'
  },
  {
    id: 'data-migration',
    slug: 'data-migration-mapper',
    name: 'Data Migration Mapper',
    description: 'Generate strict data sign-off checklists for high-stakes e-commerce migrations.',
    category: 'legal',
    icon: Database,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'MigrationMapper',
    personas: ['engineer', 'agency'],
    monthlyViews: 1050,
    usageCount: 1721,
    audience: 'Creative Studio'
  },
  {
    id: 'word-counter',
    slug: 'word-count-analysis',
    name: 'Word & Content Analyzer',
    description: 'Advanced real-time word count, reading time, and SEO keyword density analysis.',
    category: 'operations',
    icon: Type,
    tier: 'FREE',
    hasAI: false,
    component: 'RealTimeContentAnalyzer',
    personas: ['marketer', 'content-writer'],
    monthlyViews: 4100,
    usageCount: 2430,
    audience: 'Creative Studio'
  },
  {
    id: 'css-gen',
    slug: 'advanced-css-generator',
    name: 'Advanced CSS Engine',
    description: 'Generate premium Glassmorphism, Neumorphism, and multi-layered Smooth Shadows.',
    category: 'development',
    icon: LayoutDashboard,
    tier: 'FREE',
    hasAI: false,
    component: 'AdvancedCssEngine',
    personas: ['engineer', 'designer'],
    monthlyViews: 2800,
    usageCount: 724,
    audience: 'Dev Agency'
  },
  {
    id: 'contrast-checker',
    slug: 'color-contrast-checker',
    name: 'WCAG Contrast Auditor',
    description: 'Ensure your brand colors meet WCAG 2.1 accessibility standards for AA and AAA compliance.',
    category: 'development',
    icon: Palette,
    tier: 'FREE',
    hasAI: false,
    component: 'ColorContrastChecker',
    personas: ['designer', 'marketer'],
    monthlyViews: 3200,
    usageCount: 4273,
    audience: 'Creative Studio'
  },
  {
    id: 'investment-calc',
    slug: 'investment-growth-calculator',
    name: 'Freelance Wealth Builder',
    description: 'Visualize the power of compound interest and plan your agency exit strategy.',
    category: 'finance',
    icon: TrendingUp,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'FreelanceWealthBuilder',
    personas: ['founder', 'agency'],
    monthlyViews: 3800,
    usageCount: 556,
    audience: 'Dev Agency'
  },
  {
    id: 'wholesale-pricing',
    slug: 'wholesale-msrp-pricing-engine',
    name: 'Wholesale & MSRP Pricing Engine',
    description: 'Simulate wholesale margins, retailer markups, and profit splits with precision.',
    category: 'finance',
    icon: Package,
    tier: 'FREE',
    hasAI: false,
    component: 'WholesalePricingEngine',
    personas: ['founder', 'ecom'],
    monthlyViews: 2100,
    usageCount: 2631,
    audience: 'Dev Agency'
  },
  {
    id: 'fb-ads-calc',
    slug: 'facebook-ads-cpa-calculator',
    name: 'Facebook Ads CPA Calculator',
    description: 'Estimate your Facebook Ads campaign performance, conversions, and target CPA.',
    category: 'marketing',
    icon: TrendingUp,
    tier: 'FREE',
    hasAI: false,
    component: 'FbAdsCalculator',
    personas: ['media-buyer', 'agency'],
    monthlyViews: 4500,
    usageCount: 3452,
    audience: 'Solo Freelancer'
  },
  {
    id: 'email-roi-calc',
    slug: 'email-marketing-roi-calculator',
    name: 'Email Marketing ROI Calculator',
    description: 'Calculate the total revenue and ROI of your email marketing campaigns.',
    category: 'marketing',
    icon: Send,
    tier: 'FREE',
    hasAI: false,
    component: 'EmailRoiCalculator',
    personas: ['ecommerce', 'agency'],
    monthlyViews: 3200,
    usageCount: 3392,
    audience: 'Solo Freelancer'
  },
  {
    id: 'social-roi-calc',
    slug: 'social-media-ltv-calculator',
    name: 'Social Media ROI (LTV) Calculator',
    description: 'Defend your retainer by calculating the Lifetime Value (LTV) impact of social leads.',
    category: 'marketing',
    icon: Users,
    tier: 'FREE',
    hasAI: false,
    component: 'SocialRoiCalculator',
    personas: ['founder', 'agency'],
    monthlyViews: 2800,
    usageCount: 3981,
    audience: 'Dev Agency'
  },
  {
    id: 'cpm-calc',
    slug: 'ultimate-cpm-calculator',
    name: 'Ultimate CPM Calculator',
    description: 'Solve for CPM, Spend, or Impressions with our bi-directional media buying tool.',
    category: 'marketing',
    icon: Hash,
    tier: 'FREE',
    hasAI: false,
    component: 'CpmCalculator',
    personas: ['media-buyer', 'agency'],
    monthlyViews: 5100,
    usageCount: 2972,
    audience: 'Solo Freelancer'
  },
  {
    id: 'engagement-calc',
    slug: 'social-engagement-calculator',
    name: 'Engagement Rate Calculator',
    description: 'Audit the health of any social media profile using reach or follower metrics.',
    category: 'marketing',
    icon: Heart,
    tier: 'FREE',
    hasAI: false,
    component: 'EngagementCalculator',
    personas: ['media-buyer', 'agency'],
    monthlyViews: 3900,
    usageCount: 4753,
    audience: 'Creative Studio'
  },
  {
    id: 'conversion-calc',
    slug: 'conversion-rate-uplift-calculator',
    name: 'Conversion & A/B Uplift Calculator',
    description: 'Compare two variants and calculate the conversion rate uplift of your split tests.',
    category: 'marketing',
    icon: Repeat,
    tier: 'FREE',
    hasAI: false,
    component: 'ConversionCalculator',
    personas: ['media-buyer', 'agency'],
    monthlyViews: 2400,
    usageCount: 1770,
    audience: 'Dev Agency'
  },
  {
    id: 'robots-gen',
    slug: 'advanced-robots-txt-generator',
    name: 'Advanced Robots.txt Generator',
    description: 'Prevent catastrophic SEO mistakes with a validated robots.txt generator.',
    category: 'development',
    icon: ShieldCheck,
    tier: 'FREE',
    hasAI: false,
    component: 'RobotsGenerator',
    personas: ['developer', 'agency'],
    monthlyViews: 3100,
    usageCount: 704,
    audience: 'Creative Studio'
  },
  {
    id: 'html-word-count',
    slug: 'html-word-counter',
    name: 'HTML Word Counter',
    description: 'Strip code tags for accurate word counts and reading time audits.',
    category: 'development',
    icon: Type,
    tier: 'FREE',
    hasAI: false,
    component: 'HtmlWordCounter',
    personas: ['developer', 'agency'],
    monthlyViews: 2800,
    usageCount: 2526,
    audience: 'Solo Freelancer'
  },
  {
    id: 'idea-gen',
    slug: 'headline-idea-generator',
    name: 'Headline Idea Generator',
    description: 'Generate high-converting blog and email subject lines using proven templates.',
    category: 'marketing',
    icon: Zap,
    tier: 'FREE',
    hasAI: false,
    component: 'HeadlineIdeaEngine',
    personas: ['founder', 'agency'],
    monthlyViews: 4200,
    usageCount: 1656,
    audience: 'Solo Freelancer'
  },
  {
    id: 'text-diff',
    slug: 'text-diff-tool',
    name: 'Text Diff Tool',
    description: 'Instantly compare two versions of code or copy to highlight additions and deletions.',
    category: 'development',
    icon: Code,
    tier: 'FREE',
    hasAI: false,
    component: 'TextDiffTool',
    personas: ['developer', 'agency'],
    monthlyViews: 3500,
    usageCount: 1037,
    audience: 'Solo Freelancer'
  },
  {
    id: 'html-text-conv',
    slug: 'html-to-text-converter',
    name: 'HTML ↔ Text Converter',
    description: 'Clean up messy formatting or generate plain-text fallbacks for email.',
    category: 'development',
    icon: Repeat,
    tier: 'FREE',
    hasAI: false,
    component: 'HtmlTextConverter',
    personas: ['developer', 'agency'],
    monthlyViews: 2600,
    usageCount: 353,
    audience: 'Dev Agency'
  },
  {
    id: 'case-conv',
    slug: 'advanced-case-converter',
    name: 'Advanced Case Converter',
    description: 'Standardize formatting instantly with title, sentence, camel, and snake case.',
    category: 'development',
    icon: Type,
    tier: 'FREE',
    hasAI: false,
    component: 'CaseConverter',
    personas: ['developer', 'agency'],
    monthlyViews: 3800,
    usageCount: 4528,
    audience: 'Dev Agency'
  },
  {
    id: 'business-valuation',
    slug: 'business-valuation-calculator',
    name: 'Business Valuation Calculator',
    description: 'Calculate your company’s exit value based on SDE, add-backs, and industry-specific multiples.',
    category: 'finance',
    icon: Landmark,
    tier: 'FREE',
    hasAI: false,
    component: 'BusinessValuationCalculator',
    personas: ['founder', 'agency'],
    monthlyViews: 2400,
    usageCount: 1670,
    audience: 'Creative Studio'
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter-validator',
    name: 'JSON Formatter & Validator',
    description: 'Beautify, minify, and validate JSON data instantly and securely in your browser.',
    category: 'development',
    icon: Code,
    tier: 'FREE',
    hasAI: false,
    component: 'JsonFormatter',
    personas: ['engineer', 'data-scientist'],
    monthlyViews: 3200,
    usageCount: 4358,
    audience: 'Solo Freelancer'
  },
  {
    id: 'roas-calc',
    slug: 'roas-calculator',
    name: 'ROAS & Break-Even Calculator',
    description: 'Analyze ad performance, calculate net profit, and find your break-even ROAS based on margins.',
    category: 'finance',
    icon: TrendingUp,
    tier: 'FREE',
    hasAI: false,
    component: 'RoasCalculator',
    personas: ['agency', 'marketer'],
    monthlyViews: 1800,
    usageCount: 706,
    audience: 'Creative Studio'
  },
  {
    id: 'px-rem-calc',
    slug: 'px-to-rem-converter',
    name: 'PX to REM Converter',
    description: 'Convert pixels to REM units for accessible, responsive web typography.',
    category: 'development',
    icon: Type,
    tier: 'FREE',
    hasAI: false,
    component: 'PxToRemConverter',
    personas: ['engineer', 'designer'],
    monthlyViews: 2500,
    usageCount: 2411,
    audience: 'Dev Agency'
  },
  {
    id: 'http-security-auditor',
    slug: 'http-security-header-auditor',
    name: 'HTTP Security Header Auditor',
    description: 'Audit website security posture by checking for critical HTTP headers like CSP, HSTS, and X-Frame-Options.',
    category: 'security',
    icon: ShieldCheck,
    tier: 'FREE',
    hasAI: false,
    component: 'SecurityHeaderAuditor',
    personas: ['engineer', 'agency', 'designer'],
    monthlyViews: 2100,
    usageCount: 2611,
    audience: 'Dev Agency'
  },
  {
    id: 'breach-calculator',
    slug: 'data-breach-risk-calculator',
    name: 'Data Breach Risk & Cost Calculator',
    description: 'Calculate the estimated financial liability of a data breach based on record count and industry sector.',
    category: 'security',
    icon: ShieldAlert,
    tier: 'FREE',
    hasAI: false,
    component: 'BreachCalculator',
    personas: ['engineer', 'agency', 'marketing'],
    monthlyViews: 1800,
    usageCount: 868,
    audience: 'Solo Freelancer'
  },
  {
    id: 'ssl-checker',
    slug: 'ssl-checker',
    name: 'Deep-Scanning SSL Checker',
    description: 'Audit certificate installation, validate expiration dates, and scan for legacy TLS vulnerabilities across any domain.',
    category: ['security', 'development'],
    icon: ShieldCheck,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'SSLChecker',
    personas: ['engineer', 'agency'],
    monthlyViews: 1200,
    usageCount: 540,
    audience: ['Dev Agency', 'Solo Freelancer']
  },
  {
    id: 'csr-generator',
    slug: 'csr-generator',
    name: 'CSR & Private Key Generator',
    description: 'Instantly generate secure, RSA-encoded Certificate Signing Requests and Private Keys for enterprise SSL/TLS provisioning.',
    category: 'security',
    icon: Key,
    tier: 'PRO',
    hasAI: false,
    component: 'CSRGenerator',
    personas: ['engineer', 'agency'],
    monthlyViews: 1540,
    usageCount: 820,
    audience: ['Dev Agency', 'Solo Freelancer']
  },
  {
    id: 'csr-decoder',
    slug: 'csr-decoder',
    name: 'CSR & SSL Certificate Decoder',
    description: 'Decode Base64 certificate requests to verify organizational details, public keys, and algorithms before CA submission.',
    category: 'security',
    icon: FileSearch,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'CSRDecoder',
    personas: ['engineer', 'agency'],
    monthlyViews: 1040,
    usageCount: 420,
    audience: ['Dev Agency', 'Solo Freelancer']
  },
  {
    id: 'server-config',
    slug: 'server-config-generator',
    name: 'Server Config Generator',
    description: 'Generate secure .htaccess or Nginx configuration snippets to harden your web server.',
    category: 'security',
    icon: Server,
    tier: 'FREE',
    hasAI: false,
    component: 'ServerConfigGenerator',
    personas: ['engineer', 'agency'],
    monthlyViews: 1400,
    usageCount: 3942,
    audience: 'Dev Agency'
  },
  {
    id: 'dmarc-gen',
    slug: 'dmarc-spf-record-generator',
    name: 'DMARC & SPF Record Generator',
    description: 'Generate valid DNS TXT records for SPF and DMARC to improve email deliverability and security.',
    category: 'security',
    icon: ShieldCheck,
    tier: 'FREE',
    hasAI: false,
    component: 'DmarcGenerator',
    personas: ['engineer', 'agency', 'marketing'],
    monthlyViews: 1950,
    usageCount: 5076,
    audience: 'Dev Agency'
  },
  {
    id: 'wp-security-auditor',
    slug: 'wordpress-security-hardening-auditor',
    name: 'WordPress Security Auditor',
    description: 'Scan WordPress sites for common security exposures like XML-RPC, version disclosure, and default login paths.',
    category: 'security',
    icon: ShieldAlert,
    tier: 'FREE',
    hasAI: false,
    component: 'WpSecurityAuditor',
    personas: ['agency', 'engineer'],
    monthlyViews: 2400,
    usageCount: 3116,
    audience: 'Solo Freelancer'
  },
  {
    id: 'zero-trust-scoper',
    slug: 'zero-trust-architecture-scoper',
    name: '"Zero Trust" Architecture Scoper',
    description: 'Map out security perimeters and calculate implementation complexity for Zero Trust frameworks.',
    category: 'security',
    icon: ShieldCheck,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'ZeroTrustScoper',
    personas: ['engineer', 'agency'],
    monthlyViews: 1200,
    usageCount: 628,
    audience: 'Dev Agency'
  },
  {
    id: 'cookie-consent',
    slug: 'gdpr-ccpa-cookie-consent-boilerplate',
    name: 'GDPR/CCPA Cookie Consent Boilerplate',
    description: 'Generate compliant cookie consent banners and privacy notice scripts for global compliance.',
    category: 'security',
    icon: FileText,
    tier: 'FREE',
    hasAI: false,
    component: 'CookieConsent',
    personas: ['marketing', 'agency'],
    monthlyViews: 1800,
    usageCount: 4382,
    audience: 'Dev Agency'
  },
  {
    id: 'ransomware-calculator',
    slug: 'ransomware-downtime-cost-calculator',
    name: 'Ransomware Downtime Cost Calculator',
    description: 'Analyze the hourly financial impact of system downtime and data recovery during an attack.',
    category: 'security',
    icon: AlertTriangle,
    tier: 'FREE',
    hasAI: false,
    component: 'RansomwareCalculator',
    personas: ['engineer', 'agency'],
    monthlyViews: 1500,
    usageCount: 2164,
    audience: 'Creative Studio'
  },
  {
    id: 'backlink-auditor',
    slug: 'backlink-discovery-tool',
    name: 'Backlink Discovery Tool',
    description: 'Audit any domain to discover inbound links, referring domains, and anchor text distribution.',
    category: 'development',
    icon: Link,
    tier: 'FREEMIUM',
    hasAI: false,
    component: 'BacklinkAuditor',
    tags: ['SEO', 'Audit', 'CSV Export'],
    personas: ['agency', 'developer'],
    monthlyViews: 4500,
    usageCount: 1924,
    audience: 'Solo Freelancer'
  }
];
